ALTER TABLE appointments
    ADD COLUMN duration_minutes INT NOT NULL DEFAULT 30,
    ADD COLUMN emergency BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN reminder24h_sent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN reminder1h_sent BOOLEAN NOT NULL DEFAULT FALSE;
